/**
 * HLE network stub handlers for sceNet, sceNetAdhoc, sceNp, sceWlan, sceHttp.
 */

import { Logger } from "../utils/logger.js";
import type { HLEKernel } from "./hle-kernel.js";
import { NET, NET_ADHOC, NP, WLAN, HTTP, NP2, NET_ADHOC_MATCHING, NET_INET, NET_LIB, NET_RESOLVER, NP_DRM, OPENPSID, PARSE_HTTP, PARSE_URI, PAUTH, SSL } from "./nids.js";

const log = Logger.get("HLE-NET");

export function registerNetHLE(kernel: HLEKernel): void {

  // ── Stubs: HTTP ──────────────────────────────────────────────────────────
  kernel.stub(HTTP.sceHttpAbortRequest);
  kernel.stub(HTTP.sceHttpAddCookie, 1);
  kernel.stub(HTTP.sceHttpAddExtraHeader, 1);
  kernel.stub(HTTP.sceHttpCreateConnectionWithURL, 1);
  kernel.stub(HTTP.sceHttpCreateRequest, 1);
  kernel.stub(HTTP.sceHttpCreateRequestWithURL, 1);
  kernel.stub(HTTP.sceHttpCreateTemplate, 1);
  kernel.stub(HTTP.sceHttpDeleteConnection);
  kernel.stub(HTTP.sceHttpDeleteHeader);
  kernel.stub(HTTP.sceHttpDeleteRequest);
  kernel.stub(HTTP.sceHttpDeleteTemplate);
  kernel.stub(HTTP.sceHttpDisableAuth);
  kernel.stub(HTTP.sceHttpDisableCache);
  kernel.stub(HTTP.sceHttpDisableCookie);
  kernel.stub(HTTP.sceHttpDisableKeepAlive);
  kernel.stub(HTTP.sceHttpDisableRedirect);
  kernel.stub(HTTP.sceHttpEnableAuth);
  kernel.stub(HTTP.sceHttpEnableCache);
  kernel.stub(HTTP.sceHttpEnableCookie);
  kernel.stub(HTTP.sceHttpEnableKeepAlive);
  kernel.stub(HTTP.sceHttpEnableRedirect);
  kernel.stub(HTTP.sceHttpEnd);
  kernel.stub(HTTP.sceHttpEndCache);
  kernel.stub(HTTP.sceHttpGetAllHeader);
  kernel.stub(HTTP.sceHttpGetContentLength);
  kernel.stub(HTTP.sceHttpGetNetworkErrno);
  kernel.stub(HTTP.sceHttpGetNetworkPspError);
  kernel.stub(HTTP.sceHttpGetProxy);
  kernel.stub(HTTP.sceHttpGetStatusCode);
  kernel.stub(HTTP.sceHttpInit);
  kernel.stub(HTTP.sceHttpInitCache, 1);
  kernel.stub(HTTP.sceHttpReadData, 1);
  kernel.stub(HTTP.sceHttpSaveSystemCookie);
  kernel.stub(HTTP.sceHttpSendRequest);
  kernel.stub(HTTP.sceHttpSetAuthInfoCB);
  kernel.stub(HTTP.sceHttpSetAuthInfoCallback);
  kernel.stub(HTTP.sceHttpSetConnectTimeOut, 1);
  kernel.stub(HTTP.sceHttpSetMallocFunction, 1);
  kernel.stub(HTTP.sceHttpSetProxy);
  kernel.stub(HTTP.sceHttpSetRecvTimeOut);
  kernel.stub(HTTP.sceHttpSetRedirectCallback);
  kernel.stub(HTTP.sceHttpSetResolveRetry);
  kernel.stub(HTTP.sceHttpSetResolveTimeOut);
  kernel.stub(HTTP.sceHttpSetSendTimeOut);
  kernel.stub(HTTP.sceHttpsDisableOption);
  kernel.stub(HTTP.sceHttpsEnableOption);
  kernel.stub(HTTP.sceHttpsEnd);
  kernel.stub(HTTP.sceHttpsGetSslError);
  kernel.stub(HTTP.sceHttpsInit, 1);
  kernel.stub(HTTP.sceHttpsInitWithPath, 1);
  kernel.stub(HTTP.sceHttpsLoadDefaultCert, 1);
  kernel.stub(HTTP.sceHttpsSetSslCallback);
  // ── Stubs: NET ──────────────────────────────────────────────────────────
  kernel.stub(NET.__NetApctlCallbacks);
  kernel.stub(NET.sceNetInit);
  kernel.stub(NET.sceNetTerm);
  kernel.stub(NET.sceNetApctlAddHandler, 1);
  kernel.stub(NET.sceNetApctlAddInternalHandler, 1);
  kernel.stub(NET.sceNetApctlConnect, 1);
  kernel.stub(NET.sceNetApctlDelHandler);
  kernel.stub(NET.sceNetApctlDelInternalHandler);
  kernel.stub(NET.sceNetApctlDisconnect, 1);
  kernel.stub(NET.sceNetApctlGetBSSDescEntry);
  kernel.stub(NET.sceNetApctlGetBSSDescEntry2);
  kernel.stub(NET.sceNetApctlGetBSSDescEntryUser);
  kernel.stub(NET.sceNetApctlGetBSSDescIDList);
  kernel.stub(NET.sceNetApctlGetBSSDescIDList2);
  kernel.stub(NET.sceNetApctlGetBSSDescIDListUser);
  kernel.stub(NET.sceNetApctlGetInfo);
  kernel.stub(NET.sceNetApctlGetState);
  kernel.stub(NET.sceNetApctlInit, 1);
  kernel.stub(NET.sceNetApctlScan);
  kernel.stub(NET.sceNetApctlScanSSID2);
  kernel.stub(NET.sceNetApctlScanUser);
  kernel.stub(NET.sceNetApctlTerm);
  kernel.stub(NET.sceNetApctl_6F5D2981);
  kernel.stub(NET.sceNetApctl_A7BB73DF);
  kernel.stub(NET.sceNetApctl_lib2_4C19731F);
  kernel.stub(NET.sceNetApctl_lib2_69745F0A);
  kernel.stub(NET.sceNetApctl_lib2_C20A144C);
  kernel.stub(NET.sceNetEtherNtostr);
  kernel.stub(NET.sceNetEtherStrton);
  kernel.stub(NET.sceNetFreeThreadinfo);
  kernel.stub(NET.sceNetGetDropRate);
  kernel.stub(NET.sceNetGetLocalEtherAddr, 1);
  kernel.stub(NET.sceNetGetLocalEtherAddrAlt);
  kernel.stub(NET.sceNetGetMallocStat, 1);
  kernel.stub(NET.sceNetSetDropRate);
  kernel.stub(NET.sceNetThreadAbort);
  kernel.stub(NET.sceNetUpnpGetNatInfo);
  kernel.stub(NET.sceNetUpnpInit, 1);
  kernel.stub(NET.sceNetUpnpStart, 1);
  kernel.stub(NET.sceNetUpnpStop);
  kernel.stub(NET.sceNetUpnpTerm);
  kernel.stub(NET.sceWlanDevIsPowerOn);
  // ── Stubs: NET_ADHOC ──────────────────────────────────────────────────────
  kernel.stub(NET_ADHOC.__NetTriggerCallbacks);
  kernel.stub(NET_ADHOC.sceNetAdhocInit);
  kernel.stub(NET_ADHOC.sceNetAdhocTerm);
  kernel.stub(NET_ADHOC.sceNetAdhocDiscoverGetStatus);
  kernel.stub(NET_ADHOC.sceNetAdhocDiscoverInitStart, 1);
  kernel.stub(NET_ADHOC.sceNetAdhocDiscoverRequestSuspend);
  kernel.stub(NET_ADHOC.sceNetAdhocDiscoverStop);
  kernel.stub(NET_ADHOC.sceNetAdhocDiscoverTerm);
  kernel.stub(NET_ADHOC.sceNetAdhocDiscoverUpdate);
  kernel.stub(NET_ADHOC.sceNetAdhocGameModeCreateMaster, 1);
  kernel.stub(NET_ADHOC.sceNetAdhocGameModeCreateReplica, 1);
  kernel.stub(NET_ADHOC.sceNetAdhocGameModeDeleteMaster);
  kernel.stub(NET_ADHOC.sceNetAdhocGameModeDeleteReplica);
  kernel.stub(NET_ADHOC.sceNetAdhocGameModeUpdateMaster);
  kernel.stub(NET_ADHOC.sceNetAdhocGameModeUpdateReplica);
  kernel.stub(NET_ADHOC.sceNetAdhocGetPdpStat);
  kernel.stub(NET_ADHOC.sceNetAdhocGetPtpStat);
  kernel.stub(NET_ADHOC.sceNetAdhocGetSocketAlert);
  kernel.stub(NET_ADHOC.sceNetAdhocPdpCreate, 1);
  kernel.stub(NET_ADHOC.sceNetAdhocPdpDelete);
  kernel.stub(NET_ADHOC.sceNetAdhocPdpRecv);
  kernel.stub(NET_ADHOC.sceNetAdhocPdpSend);
  kernel.stub(NET_ADHOC.sceNetAdhocPollSocket);
  kernel.stub(NET_ADHOC.sceNetAdhocPtpAccept);
  kernel.stub(NET_ADHOC.sceNetAdhocPtpClose);
  kernel.stub(NET_ADHOC.sceNetAdhocPtpConnect, 1);
  kernel.stub(NET_ADHOC.sceNetAdhocPtpFlush);
  kernel.stub(NET_ADHOC.sceNetAdhocPtpListen);
  kernel.stub(NET_ADHOC.sceNetAdhocPtpOpen, 1);
  kernel.stub(NET_ADHOC.sceNetAdhocPtpRecv);
  kernel.stub(NET_ADHOC.sceNetAdhocPtpSend);
  kernel.stub(NET_ADHOC.sceNetAdhocSetSocketAlert);
  kernel.stub(NET_ADHOC.sceNetAdhocctlAddHandler, 1);
  kernel.stub(NET_ADHOC.sceNetAdhocctlConnect, 1);
  kernel.stub(NET_ADHOC.sceNetAdhocctlCreate, 1);
  kernel.stub(NET_ADHOC.sceNetAdhocctlCreateEnterGameMode, 1);
  kernel.stub(NET_ADHOC.sceNetAdhocctlCreateEnterGameModeMin, 1);
  kernel.stub(NET_ADHOC.sceNetAdhocctlDelHandler);
  kernel.stub(NET_ADHOC.sceNetAdhocctlDisconnect, 1);
  kernel.stub(NET_ADHOC.sceNetAdhocctlExitGameMode);
  kernel.stub(NET_ADHOC.sceNetAdhocctlGetAddrByName, 1);
  kernel.stub(NET_ADHOC.sceNetAdhocctlGetAdhocId);
  kernel.stub(NET_ADHOC.sceNetAdhocctlGetGameModeInfo);
  kernel.stub(NET_ADHOC.sceNetAdhocctlGetNameByAddr, 1);
  kernel.stub(NET_ADHOC.sceNetAdhocctlGetParameter);
  kernel.stub(NET_ADHOC.sceNetAdhocctlGetPeerInfo);
  kernel.stub(NET_ADHOC.sceNetAdhocctlGetPeerList);
  kernel.stub(NET_ADHOC.sceNetAdhocctlGetScanInfo);
  kernel.stub(NET_ADHOC.sceNetAdhocctlGetState);
  kernel.stub(NET_ADHOC.sceNetAdhocctlInit, 1);
  kernel.stub(NET_ADHOC.sceNetAdhocctlJoin);
  kernel.stub(NET_ADHOC.sceNetAdhocctlJoinEnterGameMode);
  kernel.stub(NET_ADHOC.sceNetAdhocctlScan);
  kernel.stub(NET_ADHOC.sceNetAdhocctlTerm);
  // ── Stubs: NP ──────────────────────────────────────────────────────────
  kernel.stub(NP.sceNpAuthAbortRequest);
  kernel.stub(NP.sceNpAuthCreateStartRequest, 1);
  kernel.stub(NP.sceNpAuthDestroyRequest);
  kernel.stub(NP.sceNpAuthGetEntitlementById);
  kernel.stub(NP.sceNpAuthGetEntitlementIdList);
  kernel.stub(NP.sceNpAuthGetMemoryStat);
  kernel.stub(NP.sceNpAuthGetTicket);
  kernel.stub(NP.sceNpAuthGetTicketParam);
  kernel.stub(NP.sceNpAuthInit, 1);
  kernel.stub(NP.sceNpAuthTerm);
  kernel.stub(NP.sceNpCommerce2AbortReq);
  kernel.stub(NP.sceNpCommerce2CreateCtx, 1);
  kernel.stub(NP.sceNpCommerce2CreateSessionCreateReq, 1);
  kernel.stub(NP.sceNpCommerce2CreateSessionGetResult, 1);
  kernel.stub(NP.sceNpCommerce2CreateSessionStart, 1);
  kernel.stub(NP.sceNpCommerce2DestroyCtx);
  kernel.stub(NP.sceNpCommerce2DestroyReq);
  kernel.stub(NP.sceNpCommerce2GetGameProductInfo);
  kernel.stub(NP.sceNpCommerce2GetGameSkuInfoFromGameProductInfo);
  kernel.stub(NP.sceNpCommerce2GetProductInfoCreateReq, 1);
  kernel.stub(NP.sceNpCommerce2GetProductInfoGetResult);
  kernel.stub(NP.sceNpCommerce2GetProductInfoStart, 1);
  kernel.stub(NP.sceNpCommerce2GetSessionInfo);
  kernel.stub(NP.sceNpCommerce2Init, 1);
  kernel.stub(NP.sceNpCommerce2InitGetProductInfoResult, 1);
  kernel.stub(NP.sceNpCommerce2Term);
  kernel.stub(NP.sceNpGetAccountRegion);
  kernel.stub(NP.sceNpGetChatRestrictionFlag);
  kernel.stub(NP.sceNpGetContentRatingFlag);
  kernel.stub(NP.sceNpGetMyLanguages);
  kernel.stub(NP.sceNpGetNpId);
  kernel.stub(NP.sceNpGetOnlineId);
  kernel.stub(NP.sceNpGetUserProfile);
  kernel.stub(NP.sceNpInit);
  kernel.stub(NP.sceNpLookupAbortTransaction);
  kernel.stub(NP.sceNpLookupCreateTransactionCtx, 1);
  kernel.stub(NP.sceNpLookupDestroyTransactionCtx);
  kernel.stub(NP.sceNpLookupTitleSmallStorage);
  kernel.stub(NP.sceNpRosterAbort);
  kernel.stub(NP.sceNpRosterAddFriendListEntry, 1);
  kernel.stub(NP.sceNpRosterCreateRequest, 1);
  kernel.stub(NP.sceNpRosterDeleteRequest);
  kernel.stub(NP.sceNpRosterGetBlockListEntry);
  kernel.stub(NP.sceNpRosterGetBlockListEntryCount);
  kernel.stub(NP.sceNpRosterGetFriendListEntry);
  kernel.stub(NP.sceNpRosterGetFriendListEntryCount);
  kernel.stub(NP.sceNpServiceGetMemoryStat);
  kernel.stub(NP.sceNpServiceInit, 1);
  kernel.stub(NP.sceNpServiceTerm);
  kernel.stub(NP.sceNpTerm);

  // ── NET_ADHOC_MATCHING ──────────────────────────────────────────────────────────
  kernel.stub(NET_ADHOC_MATCHING.__NetMatchingCallbacks);
  kernel.stub(NET_ADHOC_MATCHING.sceNetAdhocMatchingAbortSendData);
  kernel.stub(NET_ADHOC_MATCHING.sceNetAdhocMatchingCancelTarget);
  kernel.stub(NET_ADHOC_MATCHING.sceNetAdhocMatchingCancelTargetWithOpt);
  kernel.stub(NET_ADHOC_MATCHING.sceNetAdhocMatchingCreate, 1);
  kernel.stub(NET_ADHOC_MATCHING.sceNetAdhocMatchingDelete);
  kernel.stub(NET_ADHOC_MATCHING.sceNetAdhocMatchingGetHelloOpt);
  kernel.stub(NET_ADHOC_MATCHING.sceNetAdhocMatchingGetMembers);
  kernel.stub(NET_ADHOC_MATCHING.sceNetAdhocMatchingGetPoolMaxAlloc, 1);
  kernel.stub(NET_ADHOC_MATCHING.sceNetAdhocMatchingGetPoolStat);
  kernel.stub(NET_ADHOC_MATCHING.sceNetAdhocMatchingInit, 1);
  kernel.stub(NET_ADHOC_MATCHING.sceNetAdhocMatchingSelectTarget);
  kernel.stub(NET_ADHOC_MATCHING.sceNetAdhocMatchingSendData);
  kernel.stub(NET_ADHOC_MATCHING.sceNetAdhocMatchingSetHelloOpt);
  kernel.stub(NET_ADHOC_MATCHING.sceNetAdhocMatchingStart, 1);
  kernel.stub(NET_ADHOC_MATCHING.sceNetAdhocMatchingStart2, 1);
  kernel.stub(NET_ADHOC_MATCHING.sceNetAdhocMatchingStop);
  kernel.stub(NET_ADHOC_MATCHING.sceNetAdhocMatchingTerm);
  // ── NET_INET ──────────────────────────────────────────────────────────
  kernel.stub(NET_INET.sceNetInetAccept);
  kernel.stub(NET_INET.sceNetInetBind);
  kernel.stub(NET_INET.sceNetInetClose);
  kernel.stub(NET_INET.sceNetInetCloseWithRST);
  kernel.stub(NET_INET.sceNetInetConnect, 1);
  kernel.stub(NET_INET.sceNetInetGetErrno);
  kernel.stub(NET_INET.sceNetInetGetPspError);
  kernel.stub(NET_INET.sceNetInetGetTcpcbstat);
  kernel.stub(NET_INET.sceNetInetGetUdpcbstat);
  kernel.stub(NET_INET.sceNetInetGetpeername);
  kernel.stub(NET_INET.sceNetInetGetsockname);
  kernel.stub(NET_INET.sceNetInetGetsockopt);
  kernel.stub(NET_INET.sceNetInetInetAddr, 1);
  kernel.stub(NET_INET.sceNetInetInetAton);
  kernel.stub(NET_INET.sceNetInetInetNtop);
  kernel.stub(NET_INET.sceNetInetInetPton);
  kernel.stub(NET_INET.sceNetInetListen);
  kernel.stub(NET_INET.sceNetInetPoll);
  kernel.stub(NET_INET.sceNetInetRecv);
  kernel.stub(NET_INET.sceNetInetRecvfrom);
  kernel.stub(NET_INET.sceNetInetRecvmsg);
  kernel.stub(NET_INET.sceNetInetSelect);
  kernel.stub(NET_INET.sceNetInetSend);
  kernel.stub(NET_INET.sceNetInetSendmsg);
  kernel.stub(NET_INET.sceNetInetSendto);
  kernel.stub(NET_INET.sceNetInetSetsockopt);
  kernel.stub(NET_INET.sceNetInetShutdown);
  kernel.stub(NET_INET.sceNetInetSocket);
  kernel.stub(NET_INET.sceNetInetSocketAbort);
  kernel.stub(NET_INET.sceNetInetTerm);
  // ── NET_LIB ──────────────────────────────────────────────────────────
  kernel.stub(NET_LIB.sceNetMemcmp);
  kernel.stub(NET_LIB.sceNetMemmove);
  kernel.stub(NET_LIB.sceNetRand);
  kernel.stub(NET_LIB.sceNetSprintf);
  kernel.stub(NET_LIB.sceNetStrcasecmp);
  kernel.stub(NET_LIB.sceNetStrchr);
  kernel.stub(NET_LIB.sceNetStrcmp);
  kernel.stub(NET_LIB.sceNetStrcpy);
  kernel.stub(NET_LIB.sceNetStrlen);
  kernel.stub(NET_LIB.sceNetStrncmp);
  kernel.stub(NET_LIB.sceNetStrncpy);
  kernel.stub(NET_LIB.sceNetStrtoul);
  // ── NET_RESOLVER ──────────────────────────────────────────────────────────
  kernel.stub(NET_RESOLVER.sceNetResolverCreate, 1);
  kernel.stub(NET_RESOLVER.sceNetResolverDelete);
  kernel.stub(NET_RESOLVER.sceNetResolverInit, 1);
  kernel.stub(NET_RESOLVER.sceNetResolverPollAsync);
  kernel.stub(NET_RESOLVER.sceNetResolverStartAtoN, 1);
  kernel.stub(NET_RESOLVER.sceNetResolverStartAtoNAsync, 1);
  kernel.stub(NET_RESOLVER.sceNetResolverStartNtoA, 1);
  kernel.stub(NET_RESOLVER.sceNetResolverStartNtoAAsync, 1);
  kernel.stub(NET_RESOLVER.sceNetResolverStop);
  kernel.stub(NET_RESOLVER.sceNetResolverTerm);
  kernel.stub(NET_RESOLVER.sceNetResolverWaitAsync);
  // ── NP2 ──────────────────────────────────────────────────────────
  kernel.stub(NP2.sceNpMatching2AbortRequest);
  kernel.stub(NP2.sceNpMatching2ContextStart, 1);
  kernel.stub(NP2.sceNpMatching2ContextStop);
  kernel.stub(NP2.sceNpMatching2CreateContext, 1);
  kernel.stub(NP2.sceNpMatching2CreateJoinRoom, 1);
  kernel.stub(NP2.sceNpMatching2DestroyContext);
  kernel.stub(NP2.sceNpMatching2GetMemoryStat);
  kernel.stub(NP2.sceNpMatching2GetRoomDataExternalList);
  kernel.stub(NP2.sceNpMatching2GetServerIdListLocal);
  kernel.stub(NP2.sceNpMatching2GetServerInfo);
  kernel.stub(NP2.sceNpMatching2GetWorldInfoList);
  kernel.stub(NP2.sceNpMatching2Init, 1);
  kernel.stub(NP2.sceNpMatching2JoinRoom);
  kernel.stub(NP2.sceNpMatching2KickoutRoomMember);
  kernel.stub(NP2.sceNpMatching2LeaveRoom);
  kernel.stub(NP2.sceNpMatching2RegisterSignalingCallback, 1);
  kernel.stub(NP2.sceNpMatching2SearchRoom);
  kernel.stub(NP2.sceNpMatching2SendRoomChatMessage);
  kernel.stub(NP2.sceNpMatching2SetRoomDataInternal);
  kernel.stub(NP2.sceNpMatching2SignalingGetConnectionStatus, 1);
  kernel.stub(NP2.sceNpMatching2Term);
  // ── NP_DRM ──────────────────────────────────────────────────────────
  kernel.stub(NP_DRM.sceNpDrmClearLicenseeKey);
  kernel.stub(NP_DRM.sceNpDrmEdataGetDataSize);
  kernel.stub(NP_DRM.sceNpDrmEdataSetupKey);
  kernel.stub(NP_DRM.sceNpDrmOpen, 1);
  kernel.stub(NP_DRM.sceNpDrmRenameCheck);
  kernel.stub(NP_DRM.sceNpDrmSetLicenseeKey);
  // ── WLAN ──────────────────────────────────────────────────────────
  kernel.stub(WLAN.sceWlanGetEtherAddr);
  kernel.stub(WLAN.sceWlanGetSwitchState);
  // ── OPENPSID ──────────────────────────────────────────────────────────
  kernel.stub(OPENPSID.sceDdrdb_F013F8BF);
  kernel.stub(OPENPSID.sceOpenPSIDGetOpenPSID, 1);
  kernel.stub(OPENPSID.sceOpenPSIDGetPSID, 1);
  kernel.stub(OPENPSID.sceOpenPSIDGetProductCode, 1);
  // ── SSL ──────────────────────────────────────────────────────────
  kernel.stub(SSL.sceSslEnd);
  kernel.stub(SSL.sceSslGetIssuerName);
  kernel.stub(SSL.sceSslGetKeyUsage);
  kernel.stub(SSL.sceSslGetNameEntryCount);
  kernel.stub(SSL.sceSslGetNameEntryInfo);
  kernel.stub(SSL.sceSslGetNotAfter);
  kernel.stub(SSL.sceSslGetNotBefore);
  kernel.stub(SSL.sceSslGetSerialNumber);
  kernel.stub(SSL.sceSslGetSubjectName);
  kernel.stub(SSL.sceSslGetUsedMemoryCurrent);
  kernel.stub(SSL.sceSslGetUsedMemoryMax);
  kernel.stub(SSL.sceSslInit, 1);
  // ── PARSE_HTTP ──────────────────────────────────────────────────────────
  kernel.stub(PARSE_HTTP.sceParseHttpResponseHeader);
  kernel.stub(PARSE_HTTP.sceParseHttpStatusLine);
  // ── PARSE_URI ──────────────────────────────────────────────────────────
  kernel.stub(PARSE_URI.sceUriBuild, 1);
  kernel.stub(PARSE_URI.sceUriEscape);
  kernel.stub(PARSE_URI.sceUriParse);
  kernel.stub(PARSE_URI.sceUriUnescape);
  // ── PAUTH ──────────────────────────────────────────────────────────
  kernel.stub(PAUTH.scePauth_98B83B5D);
  kernel.stub(PAUTH.scePauth_F7AA47F6);

  log.info("Net HLE handlers registered");
}
